### ISSUE TITLE
Typo in final paragraph

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/rack-dynamic-paths-readme#4]
Remembering that everything is in Ruby is important.

Context: 
Now our routes are dynamic! We can just add songs, and everything else is taken care of and works for us. Remembering that everything is in Ruby is important. You have written a lot of Ruby; take comfort in your skills.

Could be: Remember that everything in Ruby is important.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this up. We updated the README.

As always thank you for contributing.
